from . import patient
from . import appointment
from . import doctor
from . import speciality
from . import consultation
from . import appointment_line
from . import dashboard
from . import prescription
from . import product